KEYCLOAK-13643. Added health and metrics configuration information.
keycloak/keycloak-community pull request #193
Opened 2020-11-19 15:10 UTC by miquelsi

2020-11-20 14:09 UTC, slaskawi approved these changes

2020-11-23 07:09 UTC, slaskawi approved these changes

2020-11-23 07:10 UTC, slaskawi commented
@abstractj Ready to be merged.

2020-11-23 11:43 UTC, pedroigor requested changes

2020-11-23 11:43 UTC, pedroigor commented on design/keycloak.x/configuration.md
> +Enabling/disabling health and metrics information is done with `metrics.enabled=true|false`.
Could you just add an example of how to enable metrics, something like that should be enough:

```
kc.[sh|bat] config --metrics-enabled=true
```

The reason I'm asking this is that this document is pretty much the best documentation we have at the moment, unfortunately.

2020-11-23 11:45 UTC, pedroigor commented on design/keycloak.x/configuration.md
> +Enabling/disabling health and metrics information is done with `metrics.enabled=true|false`.
Forget about it ..

2020-11-23 11:45 UTC, pedroigor approved these changes

2020-11-23 11:46 UTC, merged